// DocumentsView component

import React, { useState, useEffect } from 'react';
import { AgentFile, Agent } from '../../../types';
import { getAllFiles, updateFileContent, revertFileVersion, deleteFile } from '../../../services/storage/fileStorage';
import { FileText, Image as ImageIcon, Code, X, Search, FileSpreadsheet, Trash2, Edit2, RotateCcw, Clock, Save } from 'lucide-react';

interface DocumentsViewProps {
    agents: Agent[];
}

export const DocumentsView: React.FC<DocumentsViewProps> = ({ agents }) => {
    const [files, setFiles] = useState<AgentFile[]>([]);
    const [selectedFile, setSelectedFile] = useState<AgentFile | null>(null);
    const [filter, setFilter] = useState('');
    const [activeTab, setActiveTab] = useState<string>('all');

    // Editing State
    const [isEditing, setIsEditing] = useState(false);
    const [editContent, setEditContent] = useState('');
    const [showHistory, setShowHistory] = useState(false);

    useEffect(() => {
        setFiles(getAllFiles());
    }, []);

    const refreshFiles = () => {
        setFiles(getAllFiles());
        if (selectedFile) {
            const updated = getAllFiles().find(f => f.id === selectedFile.id);
            if (updated) setSelectedFile(updated);
        }
    };

    const getAgentName = (id: string) => {
        return agents.find(a => a.id === id)?.name || 'Unknown Agent';
    };

    const handleDelete = (id: string) => {
        if (confirm("Are you sure you want to delete this file?")) {
            deleteFile(id);
            setSelectedFile(null);
            refreshFiles();
        }
    };

    const handleSaveEdit = () => {
        if (selectedFile) {
            updateFileContent(selectedFile.id, editContent, "User");
            setIsEditing(false);
            refreshFiles();
        }
    };

    const handleRevert = (index: number) => {
        if (selectedFile && confirm("Revert to this version? This will create a new current version.")) {
            revertFileVersion(selectedFile.id, index);
            refreshFiles();
        }
    };

    // Filter Logic
    const filteredFiles = files.filter(f => {
        const matchesSearch = f.name.toLowerCase().includes(filter.toLowerCase());
        const matchesTab = activeTab === 'all' || f.agentId === activeTab;
        return matchesSearch && matchesTab;
    });

    const renderFileIcon = (type: string) => {
        switch (type) {
            case 'image': return <ImageIcon size={32} className="text-purple-400" />;
            case 'code': return <Code size={32} className="text-blue-400" />;
            case 'sheet': return <FileSpreadsheet size={32} className="text-green-400" />;
            default: return <FileText size={32} className="text-slate-400" />;
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-3xl font-bold text-white">Central Documents</h2>
                    <p className="text-slate-400 mt-1">Repository of all files generated by your AI team.</p>
                </div>
                <div className="relative w-64">
                    <Search className="absolute left-3 top-3.5 text-slate-500" size={18} />
                    <input
                        type="text"
                        placeholder="Search files..."
                        value={filter}
                        onChange={(e) => setFilter(e.target.value)}
                        className="w-full bg-slate-800 border border-slate-700 rounded-lg py-3 pl-10 pr-4 text-white focus:ring-2 focus:ring-primary outline-none"
                    />
                </div>
            </div>

            {/* Agent Tabs */}
            <div className="flex gap-2 overflow-x-auto pb-2 border-b border-slate-700/50">
                <button
                    onClick={() => setActiveTab('all')}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'all' ? 'bg-primary text-white' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
                >
                    All Files
                </button>
                {agents.map(agent => (
                    <button
                        key={agent.id}
                        onClick={() => setActiveTab(agent.id)}
                        className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === agent.id ? 'bg-slate-700 text-white border border-slate-500' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
                    >
                        {agent.name}
                    </button>
                ))}
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                {filteredFiles.map(file => {
                    const authorName = file.versions?.[0]?.author || getAgentName(file.agentId);
                    return (
                        <div
                            key={file.id}
                            onClick={() => {
                                setSelectedFile(file);
                                setEditContent(file.content);
                                setIsEditing(false);
                                setShowHistory(false);
                            }}
                            className="bg-card border border-slate-700 rounded-xl p-5 hover:border-primary/50 transition-all cursor-pointer group flex flex-col h-full relative"
                        >
                            <div className="flex items-start justify-between mb-4">
                                <div className="p-3 bg-slate-800 rounded-lg group-hover:bg-slate-700 transition-colors">
                                    {renderFileIcon(file.type)}
                                </div>
                                <span className="text-xs bg-slate-800 text-slate-400 px-2 py-1 rounded border border-slate-700">
                                    {file.type.toUpperCase()}
                                </span>
                            </div>

                            <h3 className="text-white font-semibold truncate mb-1" title={file.name}>{file.name}</h3>

                            <div className="mt-auto pt-4 flex items-center gap-2 border-t border-slate-700/50">
                                <span className="text-sm text-slate-400 truncate">
                                    By: {authorName}
                                </span>
                                <span className="text-xs text-slate-600 ml-auto">
                                    {new Date(file.updatedAt).toLocaleDateString()}
                                </span>
                            </div>
                        </div>
                    );
                })}

                {filteredFiles.length === 0 && (
                    <div className="col-span-full py-20 text-center border-2 border-dashed border-slate-800 rounded-xl">
                        <FileText size={48} className="mx-auto text-slate-700 mb-4" />
                        <h3 className="text-xl font-medium text-slate-500">No documents found</h3>
                        <p className="text-slate-600 mt-2">Start a meeting with an agent and ask them to create a file.</p>
                    </div>
                )}
            </div>

            {/* File Detail Modal */}
            {selectedFile && (
                <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                    <div className="bg-white rounded-xl w-full max-w-6xl h-[85vh] flex overflow-hidden shadow-2xl">

                        {/* Main Content Area */}
                        <div className="flex-1 flex flex-col min-w-0">
                            <div className="flex items-center justify-between p-4 border-b border-slate-200 bg-slate-50">
                                <div className="flex items-center gap-3">
                                    <h3 className="font-bold text-slate-800 text-lg">{selectedFile.name}</h3>
                                    <span className="text-xs font-mono bg-slate-200 px-2 py-1 rounded text-slate-600">
                                        v{(selectedFile.versions?.length || 1)}
                                    </span>
                                </div>
                                <div className="flex gap-2">
                                    {selectedFile.type !== 'image' && (
                                        <button
                                            onClick={() => setIsEditing(!isEditing)}
                                            className={`p-2 rounded-lg flex items-center gap-2 text-sm font-medium ${isEditing ? 'bg-primary text-white' : 'bg-white border border-slate-300 text-slate-700 hover:bg-slate-50'}`}
                                        >
                                            {isEditing ? <><Save size={16} /> Save Mode</> : <><Edit2 size={16} /> Edit</>}
                                        </button>
                                    )}
                                    <button
                                        onClick={() => setShowHistory(!showHistory)}
                                        className={`p-2 rounded-lg flex items-center gap-2 text-sm font-medium ${showHistory ? 'bg-slate-200 text-slate-800' : 'bg-white border border-slate-300 text-slate-700 hover:bg-slate-50'}`}
                                    >
                                        <Clock size={16} /> History
                                    </button>
                                    <div className="h-full w-[1px] bg-slate-300 mx-2"></div>
                                    <button onClick={() => handleDelete(selectedFile.id)} className="p-2 hover:bg-red-50 text-red-500 rounded-lg">
                                        <Trash2 size={20} />
                                    </button>
                                    <button onClick={() => setSelectedFile(null)} className="p-2 hover:bg-slate-200 rounded-lg text-slate-500 hover:text-slate-800">
                                        <X size={24} />
                                    </button>
                                </div>
                            </div>

                            <div className="flex-1 overflow-auto bg-slate-100 flex items-center justify-center p-8 relative">
                                {selectedFile.type === 'image' ? (
                                    <div className="flex flex-col items-center">
                                        <img
                                            src={`data:image/png;base64,${selectedFile.content}`}
                                            alt="Content"
                                            className="max-w-full max-h-[60vh] rounded-lg shadow-lg border border-slate-200 bg-white"
                                        />
                                    </div>
                                ) : (
                                    isEditing ? (
                                        <div className="w-full h-full flex flex-col">
                                            <textarea
                                                value={editContent}
                                                onChange={(e) => setEditContent(e.target.value)}
                                                className="w-full h-full p-8 rounded-lg shadow-sm border border-slate-300 text-slate-800 font-mono text-sm resize-none focus:ring-2 focus:ring-primary outline-none"
                                            />
                                            <div className="absolute bottom-10 right-10 flex gap-2">
                                                <button
                                                    onClick={() => { setIsEditing(false); setEditContent(selectedFile.content); }}
                                                    className="bg-slate-600 text-white px-4 py-2 rounded-lg shadow-lg hover:bg-slate-700"
                                                >
                                                    Cancel
                                                </button>
                                                <button
                                                    onClick={handleSaveEdit}
                                                    className="bg-primary text-white px-4 py-2 rounded-lg shadow-lg hover:bg-secondary"
                                                >
                                                    Save Changes
                                                </button>
                                            </div>
                                        </div>
                                    ) : (
                                        <pre className="bg-white p-8 rounded-lg shadow-sm border border-slate-200 text-slate-800 font-mono text-sm w-full h-full overflow-auto whitespace-pre-wrap">
                                            {selectedFile.content}
                                        </pre>
                                    )
                                )}
                            </div>
                        </div>

                        {/* History Sidebar */}
                        {showHistory && (
                            <div className="w-80 bg-white border-l border-slate-200 flex flex-col animate-in slide-in-from-right duration-200">
                                <div className="p-4 border-b border-slate-200 bg-slate-50 font-semibold text-slate-700">
                                    Version History
                                </div>
                                <div className="flex-1 overflow-y-auto p-4 space-y-4">
                                    {(selectedFile.versions || []).map((ver, idx) => (
                                        <div key={idx} className="border border-slate-200 rounded-lg p-3 hover:border-primary/50 transition-colors bg-white">
                                            <div className="flex justify-between items-start mb-2">
                                                <span className="text-xs font-bold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">v{idx + 1}</span>
                                                <span className="text-xs text-slate-500">{new Date(ver.timestamp).toLocaleDateString()}</span>
                                            </div>
                                            <div className="text-xs text-slate-600 mb-2">
                                                By: <span className="font-medium">{ver.author}</span>
                                            </div>
                                            <div className="flex gap-2">
                                                {idx < (selectedFile.versions?.length || 0) - 1 && (
                                                    <button
                                                        onClick={() => handleRevert(idx)}
                                                        className="text-xs flex items-center gap-1 text-primary hover:underline"
                                                    >
                                                        <RotateCcw size={12} /> Revert to this
                                                    </button>
                                                )}
                                                {idx === (selectedFile.versions?.length || 0) - 1 && (
                                                    <span className="text-xs text-green-600 font-medium">Current</span>
                                                )}
                                            </div>
                                        </div>
                                    )).reverse()}
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
};
